### ISSUE TITLE
Any way of configuring this?

### ISSUE THREAD

**Issue by fatso83** [codehabits/conventional-commits#11]
Is it possible to ignore certain commit messages from being checked? Currently it fails on all `Merge .*` commits, so I would like to filter those out.

**Comment by ellistarn** [comment]
Sorry -- I never finished the implementation for this project. Feel free to cut PRs if you're interested in building from here.

**Comment by fatso83** [comment]
For anyone interested, I just did a simple implementation here:
 https://github.com/diffia/conventional-commits/compare/v0.0.4...v0.0.5

Not configurable, just ignoring matching merge commit messages manually. Did add a test suite, though.
